---
# Headscale + Authelia Stack - Handlers

- name: Restart traefik
  community.docker.docker_container:
    name: "{{ headscale_authelia_traefik_container_name }}"
    state: started
    restart: true
  when: headscale_authelia_deploy_traefik | default(false) | bool

- name: Restart headscale
  community.docker.docker_container:
    name: "headscale_{{ headscale_authelia_stack_name }}"
    state: started
    restart: true

- name: Restart authelia
  community.docker.docker_container:
    name: "authelia_{{ headscale_authelia_stack_name }}"
    state: started
    restart: true

- name: Restart tailscale-router
  community.docker.docker_container:
    name: "tailscale-router_{{ headscale_authelia_stack_name }}"
    state: started
    restart: true

- name: Recreate stack
  community.docker.docker_compose_v2:
    project_src: "{{ headscale_authelia_base_data_dir }}/{{ headscale_authelia_stack_name }}"
    files:
      - "{{ headscale_authelia_stack_name }}.yml"
    state: present
    recreate: always
